DROP DATABASE IF EXISTS UTP10;
CREATE DATABASE IF NOT EXISTS UTP10;
USE UTP10;

DROP TABLE IF EXISTS USER_GROUP;
DROP TABLE IF EXISTS USER;
DROP TABLE IF EXISTS `GROUP`;


CREATE TABLE USER (
	USER_ID INTEGER NOT NULL AUTO_INCREMENT
	, USER_LOGIN VARCHAR(20) NOT NULL
	, USER_PASSWORD VARCHAR(20) NOT NULL

	, CONSTRAINT USERS_PK PRIMARY KEY(USER_ID) 	
);


CREATE TABLE `GROUP` (
	GROUP_ID INTEGER NOT NULL AUTO_INCREMENT
	, GROUP_NAME VARCHAR(20) NOT NULL
	, GROUP_DESCRIPTION TEXT NOT NULL

	, CONSTRAINT GROUPS_PK PRIMARY KEY(GROUP_ID)
);


CREATE TABLE USERS_GROUPS (
	USER_GROUP_ID INTEGER NOT NULL AUTO_INCREMENT
	, USER_ID INTEGER NOT NULL
	, GROUP_ID INTEGER NOT NULL
	
	, CONSTRAINT USERS_GROUPS_PK PRIMARY KEY(USER_GROUP_ID)
	, CONSTRAINT USERS_GROUPS_USERS_FK FOREIGN KEY(USER_ID) REFERENCES USER(USER_ID)
	, CONSTRAINT USERS_GROUPS_GROUPS_FK FOREIGN KEY(GROUP_ID) REFERENCES `GROUP`(GROUP_ID)
);