version: '3'

services:

    postgresql:
        image: postgres:latest
        container_name: postgresql
        restart: always
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            POSTGRES_DB: postgres
            PGDATA: /var/lib/postgresql/data/pgdata
        ports:
            - "5432:5432"
        volumes:
            - "postgresqldata:/var/lib/postgresql"
    
    pgadmin:
        image: dpage/pgadmin4:latest
        container_name: pgadmin4
        restart: always
        environment:
            PGADMIN_DEFAULT_EMAIL: postgres@glowacki.eu
            PGADMIN_DEFAULT_PASSWORD: postgres
        ports:
            - "5050:80"
        depends_on:
            - postgresql
        links:
            - postgresql

volumes:
    postgresqldata: